#!/bin/bash

# Define variables
IMAGE="localhost/aider-full"
HUID=$(id -u)
HGID=$(id -g)
CUID=$(podman run --rm --entrypoint /usr/bin/id $IMAGE -u)
CGID=$(podman run --rm --entrypoint /usr/bin/id $IMAGE -g)

# Error handling
set -e
echo "XAI api key: $XAI_API_KEY"
# Function to display error messages
error_exit() {
    echo "Error: $1" >&2
    exit 1
}

# Check if the container image exists
if ! podman image exists "$IMAGE"; then
    error_exit "Aider container image not found. Please run the installation script again."
fi

# Check if stdin is a TTY and set flags accordingly
TTY_FLAG=""
if [ -t 0 ] && [ -t 1 ]; then
    TTY_FLAG="-it"
else
    TTY_FLAG="-i"
fi

# Prepare volume mounts
MOUNTS="-v \"$PWD:/app:Z\" -v \"$HOME/.aider.conf.yml:/app/.aider.conf.yml:Z\""

# Execute command in container
eval podman run --rm -i ${TERM:+"-t"} \
    --uidmap +ug${CUID}:@${HUID}:1 \
    --gidmap +ug${CGID}:@${HGID}:1 \
    $MOUNTS \
    -e USER="$USER" \
    -e ALEPH_ALPHA_API_KEY \
    -e ALEPHALPHA_API_KEY \
    -e ANTHROPIC_API_KEY \
    -e ANYSCALE_API_KEY \
    -e AZURE_AI_API_KEY \
    -e AZURE_API_KEY \
    -e AZURE_OPENAI_API_KEY \
    -e BASETEN_API_KEY \
    -e CEREBRAS_API_KEY \
    -e CLARIFAI_API_KEY \
    -e CLOUDFLARE_API_KEY \
    -e CO_API_KEY \
    -e CODESTRAL_API_KEY \
    -e COHERE_API_KEY \
    -e DATABRICKS_API_KEY \
    -e DEEPINFRA_API_KEY \
    -e DEEPSEEK_API_KEY \
    -e FEATHERLESS_AI_API_KEY \
    -e FIREWORKS_AI_API_KEY \
    -e FIREWORKS_API_KEY \
    -e FIREWORKSAI_API_KEY \
    -e GEMINI_API_KEY \
    -e GROQ_API_KEY \
    -e HUGGINGFACE_API_KEY \
    -e INFINITY_API_KEY \
    -e MARITALK_API_KEY \
    -e MISTRAL_API_KEY \
    -e NEBIUS_API_KEY \
    -e NLP_CLOUD_API_KEY \
    -e NOVITA_API_KEY \
    -e NVIDIA_NIM_API_KEY \
    -e OLLAMA_API_KEY \
    -e OPENAI_API_KEY \
    -e OPENAI_LIKE_API_KEY \
    -e OPENROUTER_API_KEY \
    -e OR_API_KEY \
    -e PALM_API_KEY \
    -e PERPLEXITYAI_API_KEY \
    -e PREDIBASE_API_KEY \
    -e PROVIDER_API_KEY \
    -e REPLICATE_API_KEY \
    -e TOGETHERAI_API_KEY \
    -e VOLCENGINE_API_KEY \
    -e VOYAGE_API_KEY \
    -e WATSONX_API_KEY \
    -e WX_API_KEY \
    -e XAI_API_KEY \
    -e XINFERENCE_API_KEY \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN \
    -e AWS_REGION \
    -e AWS_DEFAULT_REGION \
    "$IMAGE" "$@"
